// <auto-generated />
namespace GradingAdministration_server.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class GradingDBv009 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GradingDBv009));
        
        string IMigrationMetadata.Id
        {
            get { return "202110121223546_GradingDB-v009"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
