// <auto-generated />
namespace Grading_Administration_Server.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class GradingDBV001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GradingDBV001));
        
        string IMigrationMetadata.Id
        {
            get { return "202110121808295_GradingDBV001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
